# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# More info at: https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel

name: Build and deploy WAR app to Azure Web App - tf-geonetwork3

# env:
#   APP_CONFIGURATION_CONNECTION_STRING: ${{ secrets.APP_CONFIGURATION_CONNECTION_STRING }}

on:
  push:
    branches:
      - 3.8.3-0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"

      - name: Build with Maven
        run: mvn -B -e package --file pom.xml -DskipTests
        # run: mvn clean install -- old

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.war"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "tf-geonetwork3"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDF2FC1A0C504CF2BAC9A228CD9822B7 }}
          package: "/usr/local/tomcat/webapps/*.war"
